coverage:
  precision: 2
  round: down
  range: 100...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: yes
        target: auto
    patch:
      default:
        enabled: yes
        target: auto

    changes: false

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
